export const ADD_TO_READ = "ADD_TO_READ";
export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
export const DELETE_FROM_READ = "DELETE_FROM_READ";
export const DELETE_FROM_FAVOURITES = "DELETE_FROM_FAVOURITES";
