export const ADD_TO_READ = "ADD_BOOK_TO_READ";
export const ADD_TO_FAVOURITES = "ADD_BOOK_TO_FAVOURITES";
export const REMOVE_FROM_FAVOURITES = "REMOVE_BOOK_FROM_FAVOURITES";
export const REMOVE_FROM_READING = "REMOVE_BOOK_FROM_READING";
export const GET_STATE = "GET_STATE";
